import{a as v,S as E,i}from"./assets/vendor-D7MeyRd-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const n of t)if(n.type==="childList")for(const g of n.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&r(g)}).observe(document,{childList:!0,subtree:!0});function s(t){const n={};return t.integrity&&(n.integrity=t.integrity),t.referrerPolicy&&(n.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?n.credentials="include":t.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function r(t){if(t.ep)return;t.ep=!0;const n=s(t);fetch(t.href,n)}})();const b="46143804-c250369a659784c87f3539553",R="https://pixabay.com/api/";async function y(e,o=1,s=20){const r=`${R}?key=${b}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=${s}`;try{return(await v.get(r)).data}catch(t){throw console.log("Error fetching images:",t),t}}let p=null;function B(e){const o=document.querySelector(".gallery"),s=e.map(r=>`
      <div class="gallery-item">
      <a href="${r.largeImageURL}">
           <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
           </a>
         </div>`).join("");o.innerHTML=s,p=new E(".gallery a")}function P(e){const o=document.querySelector(".gallery"),s=e.map(r=>`
     <div class="gallery-item">
     <a href="${r.largeImageURL}">
          <img src="${r.webformatURL}" alt="${r.tags}" loading="lazy" />
          </a>
        </div>
      `).join("");o.insertAdjacentHTML("beforeend",s),p.refresh()}const q=document.getElementById("searchForm"),I=document.querySelector(".gallery"),m=document.getElementById("loader"),u=document.getElementById("loadMoreBtn");let c="",a=1;const h=15;let f=0;const $=20,M=15;function d(e){e?m.classList.remove("hidden"):m.classList.add("hidden")}function l(e){e?u.classList.remove("hidden"):u.classList.add("hidden")}function S(){I.innerHTML=""}function L(){i.show({title:"End of Results",message:"We're sorry, but you've reached the end of search results.",color:"blue",position:"topRight"})}q.addEventListener("submit",async e=>{e.preventDefault();const o=document.getElementById("query").value.trim();if(N(),o!==c&&(c=o,a=1,S()),!o){i.show({title:"Warning",message:"No images found for this query!",color:"yellow",position:"topRight"});return}d(!0),l(!1);try{const s=a===1?$:M,r=await y(c,a,s);if(f=r.totalHits,r.hits.length===0){i.show({title:"Warning",message:"No images found for this query!",color:"yellow",position:"topRight"});return}B(r.hits),a++,a*s<f?l(!0):(l(!1),L()),w()}catch(s){console.error(s),i.show({title:"Error",message:"Failed to load images!",color:"red",position:"topRight"})}finally{d(!1)}});u.addEventListener("click",async()=>{d(!0),l(!1);try{const e=await y(c,a,h);console.log(e.hits),e.hits.length>0&&(P(e.hits),a++,w()),a*h>f?(l(!1),L()):l(!0)}catch(e){console.error("Error loading more images:",e),i.show({title:"Error",message:"Could not load more images. Please try again later.",color:"red",position:"topRight"})}finally{d(!1)}});function w(){const e=document.querySelectorAll(".gallery-item");if(e.length>=2){const{height:o}=e[0].getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}else if(e.length>0){const{height:o}=e[0].getBoundingClientRect();window.scrollBy({top:o,behavior:"smooth"})}else window.scrollBy({top:100,behavior:"smooth"})}function N(){const e=document.querySelector(".end-message");e&&e.remove()}
//# sourceMappingURL=index.js.map
