import{a as v,i as l}from"./assets/vendor-DfAVA04s.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))n(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const g of s.addedNodes)g.tagName==="LINK"&&g.rel==="modulepreload"&&n(g)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function n(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const E="46143804-c250369a659784c87f3539553",b="https://pixabay.com/api/";async function h(e,r=1,o=15){const n=`${b}?key=${E}&q=${encodeURIComponent(e)}&image_type=photo&orientation=horizontal&safesearch=true&page=${r}&per_page=${o}`;try{return(await v.get(n)).data}catch(t){throw console.log("Error fetching images:",t),t}}function q(e){const r=document.querySelector(".gallery"),o=images.map(n=>`
     <div class="gallery-item">
          <img src="${hit.webformatURL}" alt="${hit.tags}" loading="lazy" />
        </div>`).join("");r.innerHTML=o}function B(e){const r=document.querySelector(".gallery"),o=e.map(n=>`
     <div class="gallery-item">
          <img src="${n.webformatURL}" alt="${n.tags}" loading="lazy" />
        </div>
      `).join("");r.insertAdjacentHTML("beforeend",o)}const P=document.getElementById("searchForm"),p=document.querySelector(".gallery"),y=document.getElementById("loader"),m=document.getElementById("loadMoreBtn");let c="",a=1;const d=15;let f=0;function u(e){e?y.classList.remove("hidden"):y.classList.add("hidden")}function i(e){e?m.classList.remove("hidden"):m.classList.add("hidden")}function I(){p.innerHTML=""}P.addEventListener("submit",async e=>{e.preventDefault();const r=document.getElementById("query").value.trim();if(M(),r!==c&&(c=r,a=1,I()),!r){l.show({title:"Warning",message:"Please enter a search query!",color:"yellow",position:"topRight"});return}u(!0),i(!1);try{const o=await h(c,a,d);if(f=o.totalHits,o.hits.length===0){l.show({title:"Warning",message:"Please enter a search query!",color:"yellow",position:"topRight"}),i(!1);return}q(o.hits),a++,a*d<f?i(!0):(i(!1),w()),L()}catch(o){console.error(o),l.show({title:"Error",message:"Failed to load images!",color:"red",position:"topRight"})}finally{u(!1)}});m.addEventListener("click",async()=>{u(!0),i(!1);try{const e=await h(c,a,d);e.hits.length>0&&(B(e.hits),a++,L()),a*d>=f?(i(!1),w()):i(!0)}catch(e){console.error("Error loading more images:",e),l.show({title:"Error",message:"Could not load more images. Please try again later.",color:"red",position:"topRight"})}finally{u(!1)}});function L(){const e=document.querySelector(".gallery-item");if(e){const{height:r}=e.getBoundingClientRect();window.scrollBy({top:r*2,behavior:"smooth"})}else window.scrollBy({top:100,behavior:"smooth"})}function w(){const e=document.createElement("p");e.textContent="We're sorry, but you've reached the end of search results.",e.classList.add("end-message"),p.appendChild(e)}function M(){const e=document.querySelector(".end-message");e&&e.remove()}
//# sourceMappingURL=index.js.map
